default_language_version:
  python: python3.11
  node: "16.14.0"
repos:
  # Ruff is a linter and formatter that replaces flake8, isort, and black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        exclude: "scripts/.*\\.py"
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: ".ipynb"
        require_serial: true
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: check-ast
        description: Simply check whether files parse as valid python.
      - id: requirements-txt-fixer
        name: requirements-txt-fixer
        description: Sorts entries in requirements.txt
      - id: debug-statements
        name: debug-statements
        description: Check for debugger imports and py37+ breakpoint() calls in python source.
        exclude: cov_apps/raf/utils/util.py
      - id: check-merge-conflict
        name: check-merge-conflict
        description: Check for files that contain merge conflict strings.
      - id: check-added-large-files
        name: check-added-large-files
        description: Prevent giant files from being committed.
        args: ["--maxkb=1024"]
        exclude: |
          (?x)^(
          )$
      - id: detect-private-key
        name: detect-private-key
        description: Checks for the existence of private keys
      - id: check-xml
        name: check-xml
        description: Attempts to load all xml files to verify syntax.
      - id: check-json
        name: check-json
        description: Attempts to load all json files to verify syntax.
        exclude: |
          (?x)^(
              .vscode/.*|
              .devcontainer/.*
          )$
      - id: trailing-whitespace
        name: trailing-whitespace
        description: Removes trailing whitespace from files.
        exclude: ".*_pb\\.js|.*_pb\\.d\\.ts"
      - id: end-of-file-fixer
        name: end-of-file-fixer
        description: Ensures all files are either empty or end with a newline
        exclude: ".*_pb\\.js|.*_pb\\.d\\.ts"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        args:
          - "--no-editorconfig"
        types_or: [css, javascript, ts, tsx]
        additional_dependencies:
          - prettier@^2.7.1
          - prettier-plugin-organize-imports@^3.2.2
          - typescript@^4.8.4
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==22.3.0]
        args: [--nbqa-mutate]
      - id: nbqa-isort
        additional_dependencies: [isort==5.10.1]
        args: [--nbqa-mutate]
  - repo: local
    hooks:
      - id: git-branch-check
        name: Git branch name check
        description: Check that the git branch name is valid
        entry: ./scripts/git_branch_check.py
        language: python
        pass_filenames: false
        stages: [push]
      - id: prevent-commit-master
        name: Prevent commits on master
        description: Ensure we don't commit directly to master
        entry: ./scripts/prevent_commit_master.sh
        language: script
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --preserve-quotes, --implicit_start]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.2
    hooks:
      - id: clang-format
        files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|m|mm|proto|textproto|vert|cu)$
        exclude: ^generated/.*$
  # Exclude generated protos
exclude: |
  (?x)^(
    .*_pb2(_grpc)?.pyi?
  )$
